### ISSUE TITLE
Todo: refactoring TodoForm

### ISSUE THREAD

**Issue by inaohiro** [mayok/ts-react-todo#5]
TodoForm:

 - state に持つのは input のみにする
 - App の addTodo 関数で id を付与する
 - addTodo に渡されるのは Item ではなくなるので、別の interface を指定

TodoForm.tsx
```
this.props.addTodo({
        text: this.state.input,
        status: "Todo",
});
```

App.tsx
```
addTodo(e: Item2) {
    this.setState({
      todos: [...this.state.todos, Object.assign({ id: this.state.todos.length + 1 }, e)]
    });
}
```

**Comment by mayok** [comment]
コミットにも書いたけど， addTodo 関数内で this.state.todos.length +1 の + 1 をつけるとエラーになったので，原因を調べる

**Comment by mayok** [comment]
今は todo を消せないからいいけど，消せるようにしたら length とかしてると id が重複しちゃいそうでよろしくない
